<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Services\Email\RecompileOosSemanticCandidateEvidence;
use App\Support\CanonicalJson;
use Illuminate\Console\Command;
use RuntimeException;
use Throwable;

/**
 * Replay a banked candidate evidence artifact through the current compiler, making no model calls.
 *
 * A compiler change moves what the *same* model output compiles to. Truth can already absorb such a
 * change for free — `oos:adjudicate-semantic-corpus` recompiles `expected_plans` from the frozen
 * worksheet — but a candidate had no equivalent path, so measuring a compiler fix meant paying for
 * a fresh arm. That is why the compiled `content_scope` rule could be validated offline but not
 * *scored*. Candidate artifacts retain `attempts[].final_annotations` precisely so this is possible.
 *
 * Both sides must move together: the scorer refuses a candidate bound to a different corpus hash or
 * compiled by a different parser surface, so a recompiled candidate is only scoreable against a
 * corpus regenerated by the same change. Pass that corpus here.
 *
 * Deleted with the rest of the evaluation tooling at historic-import IC8 closeout.
 */
class RecompileOosSemanticCandidateEvidenceCommand extends Command
{
    protected $signature = 'oos:recompile-semantic-candidate-evidence
        {--corpus= : Adjudicated private corpus, regenerated by the same compiler change}
        {--candidate= : Banked candidate evidence artifact to replay}
        {--output= : Absolute private JSON output path}';

    protected $description = 'Recompile a banked semantic candidate artifact through the current compiler, without model calls';

    public function handle(RecompileOosSemanticCandidateEvidence $recompiler): int
    {
        try {
            $corpusPath = $this->requiredPath('corpus');
            $candidatePath = $this->requiredPath('candidate');
            $outputPath = $this->requiredPath('output', absolute: true);

            if (is_file($outputPath)) {
                throw new RuntimeException("Refusing to overwrite existing artifact {$outputPath}.");
            }

            $artifact = $recompiler->recompile($this->json($corpusPath), $this->json($candidatePath));

            if (file_put_contents($outputPath, CanonicalJson::encodeReadable($artifact).PHP_EOL) === false
                || ! chmod($outputPath, 0600)) {
                throw new RuntimeException("Could not write private artifact {$outputPath}.");
            }
        } catch (Throwable $exception) {
            $this->error($exception->getMessage());

            return self::FAILURE;
        }

        $provenance = $artifact['recompilation'];
        $changed = $provenance['sources_with_changed_compilation'];

        $this->info("Wrote recompiled candidate to {$outputPath}.");
        $this->line(sprintf('  parser surface  %s -> %s', $this->short($provenance['original_parser_surface_hash']), $this->short($provenance['recompiled_parser_surface_hash'])));
        $this->line(sprintf('  corpus          %s -> %s', $this->short($provenance['original_corpus_hash']), $this->short($provenance['recompiled_corpus_hash'])));
        $this->line(sprintf('  sources changed %d of %d', count($changed), count($artifact['results'])));

        foreach ($provenance['changed_parser_surface_files'] as $file) {
            $this->line("  surface file    {$file}");
        }

        foreach ($changed as $key) {
            $this->line("  recompiled      {$key}");
        }

        return self::SUCCESS;
    }

    private function short(mixed $hash): string
    {
        return is_string($hash) ? substr($hash, 0, 12).'…' : '(none)';
    }

    /** @return array<string, mixed> */
    private function json(string $path): array
    {
        if (! is_file($path)) {
            throw new RuntimeException("{$path} does not exist.");
        }

        $decoded = json_decode((string) file_get_contents($path), true);

        if (! is_array($decoded)) {
            throw new RuntimeException("{$path} is not a JSON object.");
        }

        return $decoded;
    }

    private function requiredPath(string $option, bool $absolute = false): string
    {
        $value = $this->option($option);

        if (! is_string($value) || $value === '') {
            throw new RuntimeException("--{$option} is required.");
        }

        if ($absolute && ! str_starts_with($value, '/')) {
            throw new RuntimeException("--{$option} must be an absolute path.");
        }

        return $value;
    }
}
