<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Meeting;
use Illuminate\Database\Seeder;

class MeetingSeeder extends Seeder
{
    public function run()
    {
        $meetings = [
            [
                'slug' => '1150',
                'type' => 'ChildrenAndYoungPeople',
                'start_time' => '18:45:00',
                'end_time' => '20:00:00',
                'day' => 'Friday',
                'location' => 'Church hall',
                'who' => '10-12 year olds',
                'pictures' => true,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2015-01-11 22:20:00',
            ],
            [
                'slug' => 'adventurers',
                'type' => 'ChildrenAndYoungPeople',
                'start_time' => '18:15:00',
                'end_time' => '19:15:00',
                'day' => 'Wednesday',
                'location' => 'Church hall',
                'who' => '6-9 year olds',
                'pictures' => false,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2019-09-03 10:56:40',
            ],
            [
                'slug' => 'baby-talk',
                'type' => 'ChildrenAndYoungPeople',
                'start_time' => '09:15:00',
                'end_time' => '11:30:00',
                'day' => 'Wednesday',
                'location' => 'Church hall',
                'who' => 'Babies, toddlers, and associated adults',
                'pictures' => true,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2015-01-09 22:21:27',
            ],
            [
                'slug' => 'bible-study',
                'type' => 'SundayAndBibleStudies',
                'start_time' => '19:30:00',
                'end_time' => '21:00:00',
                'day' => 'Tuesdays or Thursdays',
                'location' => 'Crockenhill and Swanley',
                'who' => 'All welcome',
                'pictures' => true,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2014-03-15 22:15:28',
            ],
            [
                'slug' => 'buzz-club',
                'type' => 'ChildrenAndYoungPeople',
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'day' => '5-8 August 2024',
                'location' => 'Church building',
                'who' => 'Primary school children',
                'pictures' => true,
                'leaders_phone' => null,
                'leaders_email' => 'admin@crockenhill.org',
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2015-01-09 22:21:45',
            ],
            [
                'slug' => 'carols-in-the-chequers',
                'type' => 'Occasional',
                'start_time' => null,
                'end_time' => null,
                'day' => '',
                'location' => 'The Chequers, Crockenhill',
                'who' => 'All welcome',
                'pictures' => false,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2014-08-16 18:30:41',
            ],
            [
                'slug' => 'christianity-explored',
                'type' => 'Occasional',
                'start_time' => null,
                'end_time' => null,
                'day' => '',
                'location' => '',
                'who' => 'All welcome',
                'pictures' => false,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2014-03-15 22:15:28',
            ],
            [
                'slug' => 'coffee-cup',
                'type' => 'Adults',
                'start_time' => '11:00:00',
                'end_time' => '12:00:00',
                'day' => 'Thursday',
                'location' => 'Church hall',
                'who' => 'All welcome',
                'pictures' => true,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2014-03-15 22:15:28',
            ],
            [
                'slug' => 'sunday-mornings',
                'type' => 'SundayAndBibleStudies',
                'start_time' => null,
                'end_time' => null,
                'day' => 'Sunday',
                'location' => 'Crockenhill Baptist Church',
                'who' => 'All welcome',
                'pictures' => true,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2014-03-15 22:15:28',
                'updated_at' => '2015-01-09 22:22:37',
            ],
            [
                'slug' => 'messy-church',
                'type' => 'ChildrenAndYoungPeople',
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'day' => '6 Sundays a year',
                'location' => 'Church building',
                'who' => 'All welcome',
                'pictures' => false,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2019-01-30 23:09:17',
                'updated_at' => '2019-01-30 23:09:17',
            ],
            [
                'slug' => 'prayer-meeting',
                'type' => 'SundayAndBibleStudies',
                'start_time' => '18:30:00',
                'end_time' => '19:15:00',
                'day' => 'Sundays',
                'location' => 'Zoom (ask for the link or dial-in)',
                'who' => 'All welcome',
                'pictures' => false,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2019-01-30 23:09:17',
                'updated_at' => '2019-01-30 23:09:17',
            ],
            [
                'slug' => 'sunday-evenings',
                'type' => 'SundayAndBibleStudies',
                'start_time' => '18:00:00',
                'end_time' => '19:00:00',
                'day' => 'Sunday',
                'location' => 'Crockenhill Baptist Church',
                'who' => 'All welcome',
                'pictures' => false,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2023-11-22 20:33:23',
                'updated_at' => '2023-11-22 20:33:23',
            ],
            [
                'slug' => 'family-talk',
                'type' => 'ChildrenAndYoungPeople',
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'day' => 'Sunday',
                'location' => 'Church building',
                'who' => 'Children with parents, grandparents, carers...',
                'pictures' => false,
                'leaders_phone' => null,
                'leaders_email' => null,
                'created_at' => '2024-02-27 20:37:11',
                'updated_at' => '2024-02-27 20:37:11',
            ],
        ];

        foreach ($meetings as $meeting) {
            Meeting::create($meeting);
        }
    }
}
