<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run()
    {
        $pages = [
            [
                'id' => 54,
                'slug' => 'links',
                'heading' => 'Links',
                'description' => 'Links to other organisations',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2023-11-23 21:20:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 58,
                'slug' => 'sermons',
                'heading' => 'Sermons',
                'description' => 'Recent sermons, mostly part of series working through books of the Bible .',
                'area' => 'christ',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2023-11-23 21:19:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 60,
                'slug' => 'find-us',
                'heading' => 'Find us',
                'description' => 'Directions to Crockenhill Baptist Church and details about car parking.',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2024-01-28 19:57:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 61,
                'slug' => 'history',
                'heading' => 'History',
                'description' => 'Find out about the history of Crockenhill Baptist Church',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2023-11-23 21:19:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 62,
                'slug' => 'pastor',
                'heading' => 'Pastor',
                'description' => 'Our pastor, Mark Drury, works full time for the church and is responsible for praying for us, preaching God\'s word to us and leading us to grow in our faith.',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2024-01-28 19:56:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 63,
                'slug' => 'statement-of-faith',
                'heading' => 'Statement of Faith',
                'description' => 'What we believe as a church, complete with Bible references',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2024-02-08 20:09:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 64,
                'slug' => 'what-we-believe',
                'heading' => 'What we believe',
                'description' => 'The good news of Jesus Christ',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2024-02-08 20:09:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 81,
                'slug' => 'members',
                'heading' => 'Members',
                'description' => 'The private area for members of Crockenhill Baptist Church',
                'area' => 'members',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-04-02 20:38:00',
                'updated_at' => '2017-03-26 15:24:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 85,
                'slug' => 'series',
                'heading' => 'Series',
                'description' => 'Sermons listed by series',
                'area' => 'sermons',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-04-04 14:46:00',
                'updated_at' => '2014-04-04 14:46:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 86,
                'slug' => 'preachers',
                'heading' => 'Preachers',
                'description' => 'Sermons listed by preacher',
                'area' => 'sermons',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-04-04 14:48:00',
                'updated_at' => '2014-04-04 18:16:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 87,
                'slug' => 'privacy-notice',
                'heading' => 'Privacy notice',
                'description' => 'Privacy notice',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2015-01-29 22:39:00',
                'updated_at' => '2023-12-27 21:53:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 88,
                'slug' => 'songs',
                'heading' => 'Songs',
                'description' => 'Songs sung at Crockenhill Baptist Church. This page loads slowly because of all the information it contains.',
                'area' => 'members',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2015-02-18 21:55:00',
                'updated_at' => '2016-12-29 18:02:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 89,
                'slug' => 'pages',
                'heading' => 'Pages',
                'description' => 'Admin tasks for website pages',
                'area' => 'members',
                'body' => 'lorem ipsum',
                'admin' => 'yes',
                'created_at' => null,
                'updated_at' => null,
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 90,
                'slug' => 'all',
                'heading' => 'All sermons',
                'description' => 'All sermons preached at Crockenhill Baptist Church',
                'area' => 'sermons',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => null,
                'updated_at' => null,
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 103,
                'slug' => 'baby-talk',
                'heading' => 'Baby Talk',
                'description' => 'A group for those with babies and toddlers on Wednesday mornings during term time.',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2023-11-23 21:21:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 104,
                'slug' => 'bible-study',
                'heading' => 'Bible study',
                'description' => 'Our weekly small group Bible studies.',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2023-11-23 21:21:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 106,
                'slug' => 'carols-in-the-chequers',
                'heading' => 'Carols in the Chequers',
                'description' => 'Carols in the Chequers - organised by Crockenhill Baptist Church',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2014-08-16 18:30:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 107,
                'slug' => 'christianity-explored',
                'heading' => 'Christianity Explored',
                'description' => 'Christianity Explored - a course for people exploring Christianity at Crockenhill Baptist Church',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2023-11-23 21:21:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 108,
                'slug' => 'coffee-cup',
                'heading' => 'Coffee Cup',
                'description' => 'A weekly meeting for coffee, cake and chat on Thursday mornings.',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2023-11-23 21:21:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 111,
                'slug' => 'sunday-mornings',
                'heading' => 'Sunday mornings',
                'description' => 'We meet to worship God together as a church every Sunday at 10:30am. Services involve reading the Bible, praying, singing and hearing God\'s word preached.',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2014-03-15 22:15:00',
                'updated_at' => '2023-11-23 21:20:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 114,
                'slug' => 'safeguarding-policy',
                'heading' => 'Safeguarding policy',
                'description' => 'Safeguarding policy',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => null,
                'updated_at' => null,
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 120,
                'slug' => 'sunday-evenings',
                'heading' => 'Sunday evenings',
                'description' => 'We meet on Sunday evenings at 6pm for a service mostly focussed on prayer, with a shorter sermon and fewer songs than in the morning.',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2023-11-19 15:51:00',
                'updated_at' => '2023-11-23 21:20:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 121,
                'slug' => 'data-protection-policy',
                'heading' => 'Data protection policy',
                'description' => 'Data protection policy',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2023-12-27 21:36:00',
                'updated_at' => '2023-12-27 21:36:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 122,
                'slug' => 'information-security-policy',
                'heading' => 'Information security policy',
                'description' => 'Information security policy',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2023-12-27 21:54:00',
                'updated_at' => '2023-12-27 21:55:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 123,
                'slug' => 'records-retention-policy',
                'heading' => 'Records retention policy',
                'description' => 'Records retention policy',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2023-12-27 21:56:00',
                'updated_at' => '2023-12-27 21:56:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 124,
                'slug' => 'data-breach-policy',
                'heading' => 'Data breach policy',
                'description' => 'Data breach policy',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2023-12-27 21:56:00',
                'updated_at' => '2023-12-27 21:56:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 125,
                'slug' => 'data-protection-complaints-process',
                'heading' => 'Data protection complaints process',
                'description' => 'Data protection complaints process',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2023-12-27 21:57:00',
                'updated_at' => '2023-12-27 21:57:00',
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 126,
                'slug' => 'leadership',
                'heading' => 'Leadership',
                'description' => 'Crockenhill Baptist Church is an independent congregational church. Under Christ, we are governed by the church members, and led by the officers they appoint.',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2024-01-28 19:53:00',
                'updated_at' => '2024-02-05 18:26:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 127,
                'slug' => 'policies',
                'heading' => 'Policies',
                'description' => 'To ensure the church is run biblically, wisely, and in compliance with charity law, the church has a constitution. This constitution is summarised for members in the Members\' Handbook. Additionally, to care for the church\'s members and visitors to its activities, the church has adopted several specific policies in different areas.',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2024-01-28 19:54:00',
                'updated_at' => '2024-01-28 20:14:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 128,
                'slug' => 'members-handbook',
                'heading' => 'Members\' Handbook',
                'description' => 'The members\' handbook outlines how the church is run, how to become a member, and what is expected of members.',
                'area' => 'church',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => null,
                'updated_at' => null,
                'markdown' => 'lorem ipsum',
                'navigation' => false,
            ],
            [
                'id' => 129,
                'slug' => 'family-talk',
                'heading' => 'Family Talk',
                'description' => 'Family Talk is for all the family.',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2024-02-27 20:33:00',
                'updated_at' => '2024-05-05 17:22:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
            [
                'id' => 130,
                'slug' => 'buzz-club',
                'heading' => 'Buzz Club',
                'description' => 'A summer holiday club for primary school children run by Crockenhill Baptist Church.',
                'area' => 'community',
                'body' => 'lorem ipsum',
                'admin' => 'no',
                'created_at' => '2024-05-05 17:10:00',
                'updated_at' => '2025-03-27 22:10:00',
                'markdown' => 'lorem ipsum',
                'navigation' => true,
            ],
        ];

        foreach ($pages as $page) {
            Page::create($page);
        }
    }
}
