<?php

declare(strict_types=1);

namespace App\Services\Song;

use App\Data\SongTitleMatch;
use App\Models\ChurchService;
use App\Models\Song;
use App\Support\CanonicalJson;
use App\Support\Xlsx\XlsxReader;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * Regenerates the historic hymn reconciliation from its original workbooks.
 *
 * F60 holds that the 2026-08-09 workbook cannot be production authority: it was
 * generated by a procedure that was never retained, against a development database
 * carrying unrelated import residue, and it accounts for only its date-only lane.
 * This is the retained procedure. It is read-only — it computes a disposition for
 * every statement the sources hold and writes nothing.
 *
 * Everything the result depends on is bound into it: the digest of each source
 * workbook, which workbook was authoritative for each year, the deployed song
 * catalogue's fingerprint, the service corpus it was reconciled against, and a
 * digest over the statements themselves. Regenerating against the same inputs
 * reproduces the same digests; anything that moved shows up as a changed binding
 * rather than as a quietly different answer.
 *
 * It deliberately does not decide whether the service-known lane should become
 * services. It measures the lane exactly so that decision can be taken on evidence.
 *
 * @phpstan-import-type HymnSourceAnomaly from HistoricHymnSourceWorkbookReader
 *
 * @phpstan-type HymnReconciledStatement array{
 *     fingerprint: string,
 *     used_on: string,
 *     reported_service: string|null,
 *     reported_number: string|null,
 *     reported_title: string,
 *     song_id: int|null,
 *     catalog_title: string|null,
 *     match_method: string|null,
 *     candidate_song_id: int|null,
 *     candidate_title: string|null,
 *     candidate_confidence: float|null,
 *     disposition: string,
 *     church_service_id: int|null,
 *     church_service_source: string|null,
 *     source_workbook: string,
 *     source_sheet: string,
 *     source_row: int,
 *     source_column: string
 * }
 */
class HistoricHymnReconciliation
{
    public const string DecisionRuleVersion = 'hymn-reconciliation-v2';

    /**
     * Which workbook is authoritative for each year sheet.
     *
     * The retained workbooks overlap — later snapshots restate earlier year sheets —
     * so a year has to be assigned to exactly one of them or the same service is counted
     * twice. This mapping reproduces the selection the 2026-08-09 workbook documented:
     * the 2023 snapshot for everything up to 2018 and for 2023, the standalone 2024
     * snapshot for 2024, and the latest snapshot for 2025 and 2026. The 28.12.2025 and
     * 15.03.2026 workbooks are therefore authoritative for nothing; they are still read,
     * so their digests are bound and their content is proven superseded rather than assumed so.
     */
    public const array SheetAuthority = [
        '2004' => 'Hymn Database @ 31.12.2023.xlsx',
        '2005' => 'Hymn Database @ 31.12.2023.xlsx',
        '2006' => 'Hymn Database @ 31.12.2023.xlsx',
        '2007' => 'Hymn Database @ 31.12.2023.xlsx',
        '2008' => 'Hymn Database @ 31.12.2023.xlsx',
        '2009' => 'Hymn Database @ 31.12.2023.xlsx',
        '2010' => 'Hymn Database @ 31.12.2023.xlsx',
        '2011' => 'Hymn Database @ 31.12.2023.xlsx',
        '2012' => 'Hymn Database @ 31.12.2023.xlsx',
        '2013' => 'Hymn Database @ 31.12.2023.xlsx',
        '2014' => 'Hymn Database @ 31.12.2023.xlsx',
        '2015' => 'Hymn Database @ 31.12.2023.xlsx',
        '2016' => 'Hymn Database @ 31.12.2023.xlsx',
        '2017' => 'Hymn Database @ 31.12.2023.xlsx',
        '2018' => 'Hymn Database @ 31.12.2023.xlsx',
        '2023' => 'Hymn Database @ 31.12.2023.xlsx',
        '2024' => 'Hymn database @ end of 2024.xlsx',
        '2025' => 'Hymn database @ 16.08.2026.xlsx',
        '2026' => 'Hymn database @ 16.08.2026.xlsx',
    ];

    public function __construct(
        private HistoricHymnSourceWorkbookReader $reader,
        private CatalogueTitleMatcher $titleMatcher = new CatalogueTitleMatcher,
    ) {}

    /**
     * @param  list<string>  $paths  every source workbook, authoritative or superseded
     * @param  array<int|string, string>|null  $sheetAuthority  year sheet to authoritative workbook, defaulting to the corpus policy.
     *                                                          PHP coerces a numeric array key to an int, and every year sheet is
     *                                                          named for its year, so the key type has to admit both.
     * @return array<string, mixed>
     */
    public function generate(array $paths, bool $acceptFuzzyMatches = false, ?array $sheetAuthority = null): array
    {
        if ($paths === []) {
            throw new RuntimeException('A hymn reconciliation needs at least one source workbook.');
        }

        $sheetAuthority ??= self::SheetAuthority;

        [$sources, $statements, $anomalies] = $this->readSources($paths, $sheetAuthority);
        $this->assertAuthorityIsSatisfied($sources, $sheetAuthority);

        $resolved = $this->resolveAgainstCatalogue($statements, $acceptFuzzyMatches);
        $corpus = $this->corpus();
        $reconciled = $this->reconcile($resolved, $corpus['services']);
        $duplicates = $this->duplicates($reconciled);

        return [
            'format' => 'historic-hymn-reconciliation',
            'version' => 1,
            'generated_at' => Carbon::now()->toIso8601String(),
            'policy' => [
                'decision_rule_version' => self::DecisionRuleVersion,
                'sheet_authority' => $sheetAuthority,
                'service_identity' => 'Exact date plus morning/evening, taken from the a/p cell marker. A date-only mark stays date-only and never guesses a service.',
                'song_identity' => 'Resolved against the deployed catalogue by title. Workbook song ids are never imported, so a primary-key difference cannot mislink usage.',
                'fuzzy_matches' => $acceptFuzzyMatches
                    ? 'Accepted as resolutions.'
                    : 'Recorded as candidates for review, never accepted as a resolution.',
                'order_assertion' => 'None. Source rows are in hymn-book number order and carry no order of service.',
            ],
            'sources' => $sources,
            'catalogue' => $this->catalogueBinding(),
            'corpus' => $corpus['binding'],
            'counts' => $this->counts($reconciled, $anomalies, $duplicates),
            'anomalies' => $anomalies,
            'duplicates' => $duplicates,
            'statements' => $reconciled,
            'statements_sha256' => CanonicalJson::hash($reconciled),
        ];
    }

    /**
     * Read every source, keeping only the sheets its workbook is authoritative for.
     *
     * @param  list<string>  $paths
     * @param  array<int|string, string>  $sheetAuthority
     * @return array{0: list<array<string, mixed>>, 1: list<array<string, mixed>>, 2: list<HymnSourceAnomaly>}
     */
    private function readSources(array $paths, array $sheetAuthority): array
    {
        $sources = [];
        $statements = [];
        $anomalies = [];

        foreach ($paths as $path) {
            $workbook = XlsxReader::open($path);
            $name = basename($path);
            $yearSheets = $this->reader->yearSheets($workbook);

            $authoritative = array_values(array_filter(
                $yearSheets,
                fn (string $sheet): bool => ($sheetAuthority[$sheet] ?? null) === $name,
            ));

            $reading = $this->reader->read($path, $authoritative);
            $statements = array_merge($statements, $reading['statements']);
            $anomalies = array_merge($anomalies, $reading['anomalies']);

            $sources[] = [
                'workbook' => $name,
                'sha256' => $workbook->sha256(),
                'byte_size' => filesize($path) ?: 0,
                'year_sheets' => $yearSheets,
                'authoritative_sheets' => $authoritative,
                'superseded_sheets' => array_values(array_diff($yearSheets, $authoritative)),
                'statements' => count($reading['statements']),
                'anomalies' => count($reading['anomalies']),
            ];
        }

        return [$sources, $statements, $anomalies];
    }

    /**
     * Every year the policy names must have been supplied, and claimed exactly once.
     *
     * @param  list<array<string, mixed>>  $sources
     * @param  array<int|string, string>  $sheetAuthority
     */
    private function assertAuthorityIsSatisfied(array $sources, array $sheetAuthority): void
    {
        $claimed = [];

        foreach ($sources as $source) {
            /** @var list<string> $sheets */
            $sheets = $source['authoritative_sheets'];

            foreach ($sheets as $sheet) {
                $claimed[$sheet] = ($claimed[$sheet] ?? 0) + 1;
            }
        }

        $missing = array_values(array_diff(array_keys($sheetAuthority), array_keys($claimed)));

        if ($missing !== []) {
            throw new RuntimeException(
                'No supplied workbook is authoritative for: '.implode(', ', $missing).'.'
            );
        }

        $duplicated = array_keys(array_filter($claimed, static fn (int $count): bool => $count > 1));

        if ($duplicated !== []) {
            throw new RuntimeException(
                'More than one workbook claims authority for: '.implode(', ', $duplicated).'.'
            );
        }
    }

    /**
     * Resolve each statement's song against the deployed catalogue.
     *
     * A fuzzy match is recorded as a candidate rather than accepted as a resolution.
     * The lane's own rule is that an unmatched statement waits for catalogue resolution
     * instead of being fuzzily guessed, and fuzzy matching is wrong often enough here to
     * matter: it pairs distinct hymns that merely open alike. Accepting one would put a
     * wrong song in the archive under the appearance of source-backed evidence.
     *
     * @param  list<array<string, mixed>>  $statements
     * @return list<array<string, mixed>>
     */
    private function resolveAgainstCatalogue(array $statements, bool $acceptFuzzyMatches): array
    {
        $resolver = SongTitleResolver::fromDatabase();
        $cache = [];

        return array_map(function (array $statement) use ($resolver, $acceptFuzzyMatches, &$cache): array {
            /** @var string $title */
            $title = $statement['reported_title'];
            $number = $statement['reported_number'];
            $key = $title."\0".($number ?? '');

            if (! array_key_exists($key, $cache)) {
                $cache[$key] = $this->titleMatcher->match($resolver, $title, is_string($number) ? $number : null);
            }

            $match = $cache[$key];
            $isFuzzy = $match?->matchType === SongTitleMatch::TYPE_FUZZY;
            $accepted = $match !== null && (! $isFuzzy || $acceptFuzzyMatches);

            return [
                ...$statement,
                'song_id' => $accepted ? $match->songId : null,
                'match_method' => $accepted ? $match->matchType : null,
                'catalog_title' => $accepted ? $resolver->catalogueTitle($match->songId) : null,
                'candidate_song_id' => $accepted || $match === null ? null : $match->songId,
                'candidate_title' => $accepted || $match === null ? null : $resolver->catalogueTitle($match->songId),
                'candidate_confidence' => $accepted || $match === null ? null : $match->confidence,
            ];
        }, $statements);
    }

    /**
     * The service corpus this reconciliation is measured against.
     *
     * @return array{services: array<string, array{id: int, source: string, song_ids: list<int>}>, binding: array<string, mixed>}
     */
    private function corpus(): array
    {
        $services = [];
        $membership = [];

        ChurchService::query()
            ->with(['items' => fn ($query) => $query->where('type', 'songs')->whereNull('deleted_at')])
            ->orderBy('date')
            ->orderBy('service')
            ->chunk(200, function ($chunk) use (&$services, &$membership): void {
                foreach ($chunk as $service) {
                    $songIds = $service->items
                        ->pluck('song_id')
                        ->filter()
                        ->map(fn ($id): int => (int) $id)
                        ->unique()
                        ->sort()
                        ->values()
                        ->all();
                    /** @var list<int> $songIds */
                    $key = $this->identityKey(
                        Carbon::parse($service->date)->toDateString(),
                        $service->service->value,
                    );

                    $services[$key] = [
                        'id' => (int) $service->id,
                        'source' => $service->source,
                        'song_ids' => $songIds,
                    ];

                    $membership[] = [
                        'identity' => $key,
                        'source' => $services[$key]['source'],
                        'song_ids' => $songIds,
                    ];
                }
            });

        return [
            'services' => $services,
            'binding' => [
                'connection' => DB::connection()->getName(),
                'database' => DB::connection()->getDatabaseName(),
                'service_count' => count($services),
                'song_item_count' => array_sum(array_map(
                    static fn (array $service): int => count($service['song_ids']),
                    $services,
                )),
                'membership_sha256' => CanonicalJson::hash($membership),
            ],
        ];
    }

    /**
     * @param  list<array<string, mixed>>  $statements
     * @param  array<string, array{id: int, source: string, song_ids: list<int>}>  $services
     * @return list<HymnReconciledStatement>
     */
    private function reconcile(array $statements, array $services): array
    {
        $reconciled = array_map(function (array $statement) use ($services): array {
            $service = $statement['reported_service'] === null
                ? null
                : ($services[$this->identityKey((string) $statement['used_on'], (string) $statement['reported_service'])] ?? null);

            return [
                'fingerprint' => $this->fingerprint($statement),
                'used_on' => $statement['used_on'],
                'reported_service' => $statement['reported_service'],
                'reported_number' => $statement['reported_number'],
                'reported_title' => $statement['reported_title'],
                'song_id' => $statement['song_id'],
                'catalog_title' => $statement['catalog_title'],
                'match_method' => $statement['match_method'],
                'candidate_song_id' => $statement['candidate_song_id'],
                'candidate_title' => $statement['candidate_title'],
                'candidate_confidence' => $statement['candidate_confidence'],
                'disposition' => $this->disposition($statement, $service),
                'church_service_id' => $service['id'] ?? null,
                'church_service_source' => $service['source'] ?? null,
                'source_workbook' => $statement['source_workbook'],
                'source_sheet' => $statement['source_sheet'],
                'source_row' => $statement['source_row'],
                'source_column' => $statement['source_column'],
            ];
        }, $statements);

        usort($reconciled, static fn (array $a, array $b): int => [$a['used_on'], $a['reported_service'] ?? '', $a['reported_title']]
            <=> [$b['used_on'], $b['reported_service'] ?? '', $b['reported_title']]);

        return $reconciled;
    }

    /**
     * @param  array<string, mixed>  $statement
     * @param  array{id: int, source: string, song_ids: list<int>}|null  $service
     */
    private function disposition(array $statement, ?array $service): string
    {
        if ($statement['reported_service'] === null) {
            return 'date_only_service_not_recorded';
        }

        if ($service === null) {
            return 'candidate_new_service';
        }

        if ($statement['song_id'] !== null && in_array($statement['song_id'], $service['song_ids'], true)) {
            return 'already_represented';
        }

        return 'review_on_existing_service';
    }

    /**
     * Statements that assert the same song at the same service twice.
     *
     * A year sheet runs past its own year, so one date can sit in two authoritative
     * sheets. F60 requires those decided rather than counted twice.
     *
     * @param  list<HymnReconciledStatement>  $statements
     * @return list<array<string, mixed>>
     */
    private function duplicates(array $statements): array
    {
        $seen = [];

        foreach ($statements as $statement) {
            $key = implode('|', [
                $statement['used_on'],
                $statement['reported_service'] ?? 'unknown',
                $statement['song_id'] === null
                    ? strtolower($statement['reported_title'])
                    : 'song:'.$statement['song_id'],
            ]);

            $seen[$key][] = $statement['fingerprint'];
        }

        $duplicates = [];

        foreach ($seen as $key => $fingerprints) {
            if (count($fingerprints) > 1) {
                $duplicates[] = ['identity' => $key, 'fingerprints' => $fingerprints];
            }
        }

        return $duplicates;
    }

    /**
     * @param  list<HymnReconciledStatement>  $statements
     * @param  list<HymnSourceAnomaly>  $anomalies
     * @param  list<array<string, mixed>>  $duplicates
     * @return array<string, mixed>
     */
    private function counts(array $statements, array $anomalies, array $duplicates): array
    {
        $byDisposition = [];
        $identities = [];
        $resolved = 0;
        $candidates = 0;

        foreach ($statements as $statement) {
            $byDisposition[$statement['disposition']] = ($byDisposition[$statement['disposition']] ?? 0) + 1;

            if ($statement['song_id'] !== null) {
                $resolved++;
            }

            if ($statement['candidate_song_id'] !== null) {
                $candidates++;
            }

            if ($statement['reported_service'] !== null) {
                $identities[$statement['disposition']][$this->identityKey(
                    $statement['used_on'],
                    $statement['reported_service'],
                )] = true;
            }
        }

        ksort($byDisposition);

        $anomalyKinds = [];
        foreach ($anomalies as $anomaly) {
            $anomalyKinds[$anomaly['kind']] = ($anomalyKinds[$anomaly['kind']] ?? 0) + 1;
        }

        return [
            'statements_total' => count($statements),
            'service_known' => count($statements) - ($byDisposition['date_only_service_not_recorded'] ?? 0),
            'date_only' => $byDisposition['date_only_service_not_recorded'] ?? 0,
            'catalogue_resolved' => $resolved,
            'catalogue_unresolved' => count($statements) - $resolved,
            'catalogue_fuzzy_candidates' => $candidates,
            'by_disposition' => $byDisposition,
            'identities_by_disposition' => array_map(count(...), $identities),
            'anomalies' => $anomalyKinds,
            'duplicates' => count($duplicates),
        ];
    }

    /** @param array<string, mixed> $statement */
    private function fingerprint(array $statement): string
    {
        return hash('sha256', implode('|', [
            (string) $statement['source_workbook'],
            (string) $statement['source_sheet'],
            (string) $statement['source_row'],
            (string) $statement['used_on'],
            (string) $statement['reported_title'],
        ]));
    }

    private function identityKey(string $date, string $service): string
    {
        return $date.'|'.$service;
    }

    /** @return array<string, mixed> */
    private function catalogueBinding(): array
    {
        $songs = Song::query()
            ->orderBy('id')
            ->get(['id', 'title'])
            ->map(fn (Song $song): array => ['id' => (int) $song->id, 'title' => (string) $song->title])
            ->all();

        return [
            'song_count' => count($songs),
            'fingerprint' => CanonicalJson::hash($songs),
        ];
    }
}
