<?php

declare(strict_types=1);

use App\Enums\SermonService;

return [
    'may24' => [
        'label' => '24 May 2026 (simpler)',
        'video' => 'Sunday 24th May 2026.mp4',
        'date' => '2026-05-24',
        'service' => SermonService::Morning,
        'pid_file' => 'run24may_pid.txt',
        'expected_service_id' => 791,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 10,
        'expected_confirmed_songs' => 2,
        'expected_childrens_talks' => 0,
        'expected_sermon_range' => [2003.0, 4189.0],
    ],
    'jun14' => [
        'label' => '14 June 2026 (complex, children\'s talk)',
        'video' => 'Sunday 14th June 2026.mp4',
        'date' => '2026-06-14',
        'service' => SermonService::Morning,
        'pid_file' => 'phase2_pid.txt',
        'expected_service_id' => 790,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 20,
        'expected_confirmed_songs' => 4,
        'expected_childrens_talks' => 1,
        'expected_sermon_range' => [2420.0, 4128.0],
    ],
    'apr23' => [
        'label' => '30 April 2023',
        'video' => 'Sunday 30th April 2023.mp4',
        'date' => '2023-04-30',
        'service' => SermonService::Morning,
        'pid_file' => 'run30apr23_pid.txt',
        'expected_service_id' => 481,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 13,
        'expected_confirmed_songs' => 4,
        'expected_childrens_talks' => 1,
        'expected_sermon_range' => [2143.0, 4001.0],
    ],
    'jan24' => [
        'label' => '21 January 2024',
        'video' => 'Sunday 21st January 2024.mp4',
        'date' => '2024-01-21',
        'service' => SermonService::Morning,
        'pid_file' => 'run21jan24_pid.txt',
        'expected_service_id' => 546,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 21,
        'expected_confirmed_songs' => 4,
        'expected_childrens_talks' => 1,
        'expected_sermon_range' => [1964.0, 3744.0],
    ],
    'nov24' => [
        // Known pipeline failure (F10): RMS under-segmentation collapses entire service into 3 sections.
        // Update these assertions once F10 is resolved.
        'label' => '17 November 2024',
        'video' => 'Sunday 17th November 2024.mp4',
        'date' => '2024-11-17',
        'service' => SermonService::Morning,
        'pid_file' => 'run17nov24_pid.txt',
        'expected_service_id' => 607,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 3,
        'expected_confirmed_songs' => 1,
        'expected_childrens_talks' => 0,
        'expected_sermon_range' => [0.0, 3916.0],
    ],
    'mar25' => [
        'label' => '16 March 2025 (Heidelberg Catechism)',
        'video' => '10-30.mkv',
        'date' => '2025-03-16',
        'service' => SermonService::Morning,
        'pid_file' => 'run16mar25_pid.txt',
        'expected_service_id' => 635,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 18,
        'expected_confirmed_songs' => 3,
        'expected_childrens_talks' => 1,
        'expected_sermon_range' => [2280.0, 3855.0],
    ],
    'sep25' => [
        'label' => '28 September 2025 (children\'s talk)',
        'video' => '10-31_2.mkv',
        'date' => '2025-09-28',
        'service' => SermonService::Morning,
        'pid_file' => 'run28sep25_pid.txt',
        'expected_service_id' => 688,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 16,
        'expected_confirmed_songs' => 4,
        'expected_childrens_talks' => 1,
        'expected_sermon_range' => [2557.0, 4742.0],
    ],
    'dec25' => [
        'label' => '28 December 2025 (post-Christmas)',
        'video' => '10-30 2.mkv',
        'date' => '2025-12-28',
        'service' => SermonService::Morning,
        'pid_file' => 'run28dec25_pid.txt',
        'expected_service_id' => 713,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 18,
        'expected_confirmed_songs' => 1,
        'expected_childrens_talks' => 1,
        'expected_sermon_range' => [2255.0, 4172.0],
    ],
    'mar26' => [
        'label' => '22 March 2026',
        'video' => '10-37.mkv',
        'date' => '2026-03-22',
        'service' => SermonService::Morning,
        'pid_file' => 'run22mar26_pid.txt',
        'expected_service_id' => 735,
        'expected_status' => 'processing',
        'expected_step' => 'extraction_complete',
        'expected_section_count' => 13,
        'expected_confirmed_songs' => 4,
        'expected_childrens_talks' => 1,
        'expected_sermon_range' => [2094.0, 3943.0],
    ],
];
